version: '2'

services:
  serilog-example:
    build:
      context: .
    environment: 
      USE_LOGSPOUT:
      LOGSTASH_FIELDS: mri.category=log,mri.product=elk_demos,mri.environment=staging,mri.application=elk_demos_serilog
    networks:
      - elastic-stack_elk

networks: 
  elastic-stack_elk:
    external: true